### ISSUE TITLE
local path in playbook example

### ISSUE THREAD

**Issue by lonico** [DeepuNetApp/aws_cvo#2]
https://github.com/DeepuNetApp/netappcvo_aws_Ansible/blob/c4bb52f6a8d412df6796d4105a6871c4faefd9cd/aws_connector.yml#L16

Maybe you could replace it with
```
  - host_vars/{{ name }}.yml
```

**Comment by lonico** [comment]
same issue with
https://github.com/DeepuNetApp/netappcvo_aws_Ansible/blob/c4bb52f6a8d412df6796d4105a6871c4faefd9cd/aws_cvo_single.yml#L14

**Comment by DeepuNetApp** [comment]
Commited the requested changes
